create table if not exists public.subscription_renewal_reminder_deliveries (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  billing_period text not null check (billing_period in ('monthly', 'quarterly', 'yearly')),
  subscription_ends_on date not null,
  reminder_day date not null default current_date,
  days_until_end integer not null check (days_until_end >= 0),
  notification_id bigint references public.notifications(id) on delete set null,
  recipient_count integer not null default 0 check (recipient_count >= 0),
  email_count integer not null default 0 check (email_count >= 0),
  push_count integer not null default 0 check (push_count >= 0),
  status text not null default 'created' check (status in ('created', 'sent', 'partial', 'failed')),
  error_message text,
  created_at timestamptz not null default now(),
  unique (school_id, subscription_ends_on, reminder_day)
);

create index if not exists subscription_renewal_reminder_deliveries_school_idx
  on public.subscription_renewal_reminder_deliveries (school_id, created_at desc);

alter table public.subscription_renewal_reminder_deliveries enable row level security;
revoke all on public.subscription_renewal_reminder_deliveries from public, anon, authenticated;
grant select on public.subscription_renewal_reminder_deliveries to authenticated;

drop policy if exists "platform super admins view subscription renewal reminder deliveries"
on public.subscription_renewal_reminder_deliveries;

create policy "platform super admins view subscription renewal reminder deliveries"
on public.subscription_renewal_reminder_deliveries for select to authenticated
using (public.is_platform_super_admin());
