create extension if not exists pgcrypto;

create table public.schools (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  school_id uuid not null references public.schools(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('admin', 'staff', 'parent')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.training_groups (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, name)
);

create table public.students (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  group_id uuid references public.training_groups(id) on delete set null,
  guardian_user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  birth_date date,
  position text check (position is null or position in ('Kaleci', 'Defans', 'Orta saha', 'Forvet')),
  guardian_name text,
  phone text,
  email text,
  address text,
  notes text,
  enrollment_date date not null default current_date,
  fee_tracking_start_date date,
  attendance_rate numeric(5,2) not null default 0 check (attendance_rate between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.fee_periods (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  fee_month date not null check (fee_month = date_trunc('month', fee_month)::date),
  status text not null default 'none' check (status in ('none', 'late', 'paid', 'exempt', 'unknown')),
  amount numeric(12,2),
  due_date date,
  paid_at timestamptz,
  payment_method text check (payment_method is null or payment_method in ('cash', 'transfer', 'card')),
  note text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, fee_month)
);

create table public.trainings (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  group_id uuid not null references public.training_groups(id) on delete restrict,
  training_date date not null,
  start_time time not null,
  duration_minutes integer not null default 90 check (duration_minutes > 0),
  title text not null,
  coach text not null,
  field text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.attendance_sessions (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  training_id bigint not null unique references public.trainings(id) on delete cascade,
  taken_by uuid references auth.users(id) on delete set null,
  taken_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.attendance_records (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.attendance_sessions(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  present boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, student_id)
);

create table public.accounting_entries (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  student_id bigint references public.students(id) on delete set null,
  fee_period_id bigint references public.fee_periods(id) on delete set null,
  occurred_on date not null default current_date,
  title text not null,
  kind text not null check (kind in ('income', 'expense')),
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null default 'cash' check (payment_method in ('cash', 'transfer', 'card')),
  source text,
  reference text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index accounting_entries_school_reference_key
  on public.accounting_entries (school_id, reference)
  where reference is not null;

create table public.notifications (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  audience text not null,
  title text not null,
  body text not null,
  status text not null default 'draft' check (status in ('draft', 'queued', 'sent', 'failed')),
  sent_by uuid references auth.users(id) on delete set null,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_secret text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index students_school_id_idx on public.students (school_id);
create index students_group_id_idx on public.students (group_id);
create index students_guardian_user_id_idx on public.students (guardian_user_id);
create index fee_periods_school_id_idx on public.fee_periods (school_id);
create index fee_periods_student_id_idx on public.fee_periods (student_id);
create index trainings_school_date_idx on public.trainings (school_id, training_date, start_time);
create index attendance_records_student_id_idx on public.attendance_records (student_id);
create index accounting_entries_school_date_idx on public.accounting_entries (school_id, occurred_on);
create index notifications_school_created_idx on public.notifications (school_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger schools_set_updated_at before update on public.schools
for each row execute function public.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger training_groups_set_updated_at before update on public.training_groups
for each row execute function public.set_updated_at();
create trigger students_set_updated_at before update on public.students
for each row execute function public.set_updated_at();
create trigger fee_periods_set_updated_at before update on public.fee_periods
for each row execute function public.set_updated_at();
create trigger trainings_set_updated_at before update on public.trainings
for each row execute function public.set_updated_at();
create trigger attendance_sessions_set_updated_at before update on public.attendance_sessions
for each row execute function public.set_updated_at();
create trigger attendance_records_set_updated_at before update on public.attendance_records
for each row execute function public.set_updated_at();
create trigger accounting_entries_set_updated_at before update on public.accounting_entries
for each row execute function public.set_updated_at();
create trigger notifications_set_updated_at before update on public.notifications
for each row execute function public.set_updated_at();
create trigger push_subscriptions_set_updated_at before update on public.push_subscriptions
for each row execute function public.set_updated_at();

create or replace function public.current_school_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select school_id from public.profiles where id = auth.uid()
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.is_school_staff(target_school_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_school_id() = target_school_id
    and public.current_user_role() in ('admin', 'staff')
$$;

create or replace function public.is_school_admin(target_school_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_school_id() = target_school_id
    and public.current_user_role() = 'admin'
$$;

revoke all on function public.current_school_id() from public;
revoke all on function public.current_user_role() from public;
revoke all on function public.is_school_staff(uuid) from public;
revoke all on function public.is_school_admin(uuid) from public;
grant execute on function public.current_school_id() to authenticated;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_school_staff(uuid) to authenticated;
grant execute on function public.is_school_admin(uuid) to authenticated;

alter table public.schools enable row level security;
alter table public.profiles enable row level security;
alter table public.training_groups enable row level security;
alter table public.students enable row level security;
alter table public.fee_periods enable row level security;
alter table public.trainings enable row level security;
alter table public.attendance_sessions enable row level security;
alter table public.attendance_records enable row level security;
alter table public.accounting_entries enable row level security;
alter table public.notifications enable row level security;
alter table public.push_subscriptions enable row level security;

create policy "school members can view school"
on public.schools for select to authenticated
using (id = public.current_school_id());

create policy "users can view own profile"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_school_staff(school_id));

create policy "admins can manage profiles"
on public.profiles for all to authenticated
using (public.is_school_admin(school_id))
with check (public.is_school_admin(school_id));

create policy "members can view groups"
on public.training_groups for select to authenticated
using (school_id = public.current_school_id());

create policy "staff can manage groups"
on public.training_groups for all to authenticated
using (public.is_school_staff(school_id))
with check (public.is_school_staff(school_id));

create policy "staff and guardians can view students"
on public.students for select to authenticated
using (public.is_school_staff(school_id) or guardian_user_id = auth.uid());

create policy "staff can manage students"
on public.students for all to authenticated
using (public.is_school_staff(school_id))
with check (public.is_school_staff(school_id));

create policy "staff and guardians can view fees"
on public.fee_periods for select to authenticated
using (
  public.is_school_staff(school_id)
  or exists (
    select 1 from public.students
    where students.id = fee_periods.student_id
      and students.guardian_user_id = auth.uid()
  )
);

create policy "staff can manage fees"
on public.fee_periods for all to authenticated
using (public.is_school_staff(school_id))
with check (public.is_school_staff(school_id));

create policy "members can view trainings"
on public.trainings for select to authenticated
using (school_id = public.current_school_id());

create policy "staff can manage trainings"
on public.trainings for all to authenticated
using (public.is_school_staff(school_id))
with check (public.is_school_staff(school_id));

create policy "members can view attendance sessions"
on public.attendance_sessions for select to authenticated
using (school_id = public.current_school_id());

create policy "staff can manage attendance sessions"
on public.attendance_sessions for all to authenticated
using (public.is_school_staff(school_id))
with check (public.is_school_staff(school_id));

create policy "staff and guardians can view attendance records"
on public.attendance_records for select to authenticated
using (
  exists (
    select 1
    from public.attendance_sessions
    join public.trainings on trainings.id = attendance_sessions.training_id
    where attendance_sessions.id = attendance_records.session_id
      and public.is_school_staff(trainings.school_id)
  )
  or exists (
    select 1 from public.students
    where students.id = attendance_records.student_id
      and students.guardian_user_id = auth.uid()
  )
);

create policy "staff can manage attendance records"
on public.attendance_records for all to authenticated
using (
  exists (
    select 1
    from public.attendance_sessions
    where attendance_sessions.id = attendance_records.session_id
      and public.is_school_staff(attendance_sessions.school_id)
  )
)
with check (
  exists (
    select 1
    from public.attendance_sessions
    where attendance_sessions.id = attendance_records.session_id
      and public.is_school_staff(attendance_sessions.school_id)
  )
);

create policy "admins can view accounting"
on public.accounting_entries for select to authenticated
using (public.is_school_admin(school_id));

create policy "admins can manage accounting"
on public.accounting_entries for all to authenticated
using (public.is_school_admin(school_id))
with check (public.is_school_admin(school_id));

create policy "members can view notifications"
on public.notifications for select to authenticated
using (school_id = public.current_school_id());

create policy "staff can manage notifications"
on public.notifications for all to authenticated
using (public.is_school_staff(school_id))
with check (public.is_school_staff(school_id));

create policy "users can manage own push subscriptions"
on public.push_subscriptions for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

insert into public.schools (name, slug)
values ('Sasa Futbol Okul Yönetim Sistemi', 'sasa-futbol');

insert into public.training_groups (school_id, name, sort_order)
select schools.id, groups.name, groups.sort_order
from public.schools
cross join (
  values
    ('Saat 09:00', 1),
    ('Saat 10:00', 2),
    ('Saat 11:00', 3),
    ('Saat 12:00', 4),
    ('U11', 5),
    ('U12', 6),
    ('U13', 7),
    ('U14', 8)
) as groups(name, sort_order)
where schools.slug = 'sasa-futbol';

