create table public.fcm_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  device_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index fcm_tokens_user_id_idx on public.fcm_tokens (user_id);

create trigger fcm_tokens_set_updated_at before update on public.fcm_tokens
for each row execute function public.set_updated_at();

alter table public.fcm_tokens enable row level security;

create policy "users can view own fcm tokens"
on public.fcm_tokens for select to authenticated
using (user_id = auth.uid());

create policy "users can delete own fcm tokens"
on public.fcm_tokens for delete to authenticated
using (user_id = auth.uid());

grant select, delete on public.fcm_tokens to authenticated;

create or replace function public.register_fcm_token(
  fcm_registration_token text,
  fcm_device_name text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  registered_token_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Oturum açmanız gerekiyor.';
  end if;

  if nullif(trim(fcm_registration_token), '') is null then
    raise exception 'Firebase cihaz anahtarı eksik.';
  end if;

  -- Firebase anahtarı cihazı temsil eder. Aynı cihazda hesap değiştirildiğinde
  -- bildirimlerin eski kullanıcıya gitmemesi için anahtar aktif hesaba devredilir.
  delete from public.fcm_tokens
  where token = fcm_registration_token;

  insert into public.fcm_tokens (
    user_id,
    token,
    device_name,
    updated_at
  ) values (
    auth.uid(),
    fcm_registration_token,
    fcm_device_name,
    now()
  )
  returning id into registered_token_id;

  return registered_token_id;
end;
$$;

revoke all on function public.register_fcm_token(text, text) from public;
grant execute on function public.register_fcm_token(text, text) to authenticated;
