create table public.access_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  school_id uuid not null references public.schools(id) on delete cascade,
  email text not null,
  full_name text not null,
  requested_role text not null check (requested_role in ('staff', 'parent')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index access_requests_school_status_idx
  on public.access_requests (school_id, status, created_at desc);

create trigger access_requests_set_updated_at before update on public.access_requests
for each row execute function public.set_updated_at();

alter table public.access_requests enable row level security;

create policy "users can view own access request"
on public.access_requests for select to authenticated
using (user_id = auth.uid());

create policy "admins can view school access requests"
on public.access_requests for select to authenticated
using (public.is_school_admin(school_id));

create or replace function public.create_access_request_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_school_id uuid;
  requested_role text;
begin
  if coalesce(new.raw_user_meta_data ->> 'access_request', 'false') <> 'true' then
    return new;
  end if;

  requested_role := new.raw_user_meta_data ->> 'requested_role';
  if requested_role not in ('staff', 'parent') then
    requested_role := 'parent';
  end if;

  select id into target_school_id
  from public.schools
  where slug = 'sasa-futbol'
  limit 1;

  if target_school_id is null then
    raise exception 'Sasa Futbol okul kaydı bulunamadı';
  end if;

  insert into public.access_requests (
    user_id,
    school_id,
    email,
    full_name,
    requested_role
  )
  values (
    new.id,
    target_school_id,
    new.email,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(new.email, '@', 1)),
    requested_role
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists create_access_request_after_auth_user on auth.users;
create trigger create_access_request_after_auth_user
after insert on auth.users
for each row execute function public.create_access_request_for_new_user();

create or replace function public.approve_access_request(
  target_request_id bigint,
  approved_role text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_row public.access_requests%rowtype;
begin
  if approved_role not in ('staff', 'parent') then
    raise exception 'Geçersiz kullanıcı rolü';
  end if;

  select *
  into request_row
  from public.access_requests
  where id = target_request_id
  for update;

  if request_row.id is null then
    raise exception 'Erişim talebi bulunamadı';
  end if;

  if not public.is_school_admin(request_row.school_id) then
    raise exception 'Bu işlem için admin yetkisi gereklidir';
  end if;

  insert into public.profiles (id, school_id, full_name, role)
  values (request_row.user_id, request_row.school_id, request_row.full_name, approved_role)
  on conflict (id) do update
  set
    school_id = excluded.school_id,
    full_name = excluded.full_name,
    role = excluded.role,
    updated_at = now();

  update public.access_requests
  set
    requested_role = approved_role,
    status = 'approved',
    reviewed_by = auth.uid(),
    reviewed_at = now()
  where id = request_row.id;
end;
$$;

create or replace function public.reject_access_request(target_request_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_row public.access_requests%rowtype;
begin
  select *
  into request_row
  from public.access_requests
  where id = target_request_id
  for update;

  if request_row.id is null then
    raise exception 'Erişim talebi bulunamadı';
  end if;

  if not public.is_school_admin(request_row.school_id) then
    raise exception 'Bu işlem için admin yetkisi gereklidir';
  end if;

  update public.access_requests
  set
    status = 'rejected',
    reviewed_by = auth.uid(),
    reviewed_at = now()
  where id = request_row.id;
end;
$$;

revoke all on function public.create_access_request_for_new_user() from public;
revoke all on function public.approve_access_request(bigint, text) from public;
revoke all on function public.reject_access_request(bigint) from public;
grant execute on function public.approve_access_request(bigint, text) to authenticated;
grant execute on function public.reject_access_request(bigint) to authenticated;
